export COLORTERM=truecolor

setopt noextendedglob

update_title() {
    print -Pn "\e]2;%m:%2~\a"
}

autoload -U add-zsh-hook
add-zsh-hook -Uz chpwd update_title

update_title

FZF_DEFAULT_OPTS="--layout=reverse"

if command -v fnm >/dev/null; then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi

if [ -d "$HOME/.sdkman" ]; then
  source "$HOME/.sdkman/bin/sdkman-init.sh"
fi
