#!/bin/sh

sxhkd -c /home/yuki/.config/sxhkd/sxhkdrc &
xscreensaver -no-splash &
compton --config /home/yuki/.config/compton/compton.conf -b
nitrogen --restore
polybar --reload yuki &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width          3
bspc config window_gap            16

bspc config normal_border_color   '#111111'
bspc config active_border_color   '#111111'
bspc config focused_border_color  '#111111'

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
