#!/bin/sh

sxhkd -c /home/yuki/.config/sxhkd/sxhkdrc &
tint2 &
xscreensaver -no-splash &
compton --config /home/yuki/.config/compton/compton.conf -b
nitrogen --restore

bspc monitor -d 一 二 三 四 六 七 八 九 十

bspc config border_width          1
bspc config window_gap            16

bspc config normal_border_color   '#c1baba'
bspc config active_border_color   '#c1baba'
bspc config focused_border_color  '#03a9f4'

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
